---
version: '3.8'
services:
  #MKDocs documentation on docker
    documentation:
        platform: linux/amd64
        build:
            dockerfile: ./Docker/test.dockerfile
            context: .
        container_name: mkdocs
        # env_file:
        #     - .env
        restart: always
        # environment:
        #     APP_DOCKER_PORT: ${APP_DOCKER_PORT:-8044}
        ports:
            - ${APP_DOCKER_PORT:-8044}:8000
